### ISSUE TITLE
Problem with vsp_real_script.py

### ISSUE THREAD

**Issue by SoftologyPro** [naver-ai/StyleKeeper#7]
I git clone the latest repo.

Running this works.
`python vsp_script.py --style fire`

Running this fails.  I put one png image under an input subfolder I created.
`python vsp_real_script.py --img_path .\input`

Gives this error.
```
Traceback (most recent call last):
  File "D:\Tests\Visual-Style-Prompting\vsp_real_script.py", line 115, in <module>
    ref_prompt = blip_inf_prompt(real_img)
  File "D:\Tests\Visual-Style-Prompting\vsp_real_script.py", line 54, in blip_inf_prompt
    generated_ids = blip_model.generate(**inputs)
  File "D:\Tests\Visual-Style-Prompting\voc_visualstyleprompting\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Tests\Visual-Style-Prompting\voc_visualstyleprompting\lib\site-packages\transformers\models\blip_2\modeling_blip_2.py", line 1830, in generate
    outputs = self.language_model.generate(
  File "D:\Tests\Visual-Style-Prompting\voc_visualstyleprompting\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Tests\Visual-Style-Prompting\voc_visualstyleprompting\lib\site-packages\transformers\generation\utils.py", line 1466, in generate
    self._validate_generated_length(generation_config, input_ids_length, has_default_max_length)
  File "D:\Tests\Visual-Style-Prompting\voc_visualstyleprompting\lib\site-packages\transformers\generation\utils.py", line 1186, in _validate_generated_length
    raise ValueError(
ValueError: Input length of input_ids is 0, but `max_length` is set to -13. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.
```

Just in case this helps, these are the commands I used when setting up a local venv to run the scripts under.
```
python -m pip install --upgrade pip
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts wheel==0.41.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts diffusers==0.27.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts accelerate==0.28.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts transformers==4.38.2
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts einops==0.7.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts kornia==0.7.2
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts gradio==4.21.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts xformers==0.0.16
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts opencv-python==4.9.0.80
pip uninstall -y torch
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
```

**Comment by SoftologyPro** [comment]
Fixed.  Needs these package versions to run local.  Create a new empty venv, run these commands.

```
python -m pip install --upgrade pip
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts wheel==0.41.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts diffusers==0.27.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts accelerate==0.28.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts einops==0.7.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts kornia==0.7.2
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts gradio==4.25.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts transformers==4.39.3
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts opencv-python==4.9.0.80
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts xformers==0.0.25 --index-url https://download.pytorch.org/whl/cu118
pip uninstall -y torch
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.2.1+cu118 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by smg1024** [comment]
Which python version did you use?
